// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SharedController from "./shared_controller"
application.register("shared", SharedController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

import IssuesController from "./issues_controller"
application.register("issues", IssuesController)
